### ISSUE TITLE
failed on 获取网页失败

### ISSUE THREAD

**Issue by SeekPoint** [leo8916/wxhub#11]
driver.get(Urls.index)
    url = driver.current_url
    if 'token' not in url:
        raise Exception(f"获取网页失败!")
    Session.token = re.findall(r'token=(\w+)', url)[0]
    process_input()
    pipe()

**Comment by SeekPoint** [comment]
似乎chrome会刷新一下，然后就推出了


G:\ub16_web_prj\wxhub>python wxhub.py -biz 大可创业
************

DevTools listening on ws://127.0.0.1:57108/devtools/browser/30c0fcb5-0575-4d01-b058-8e1948b89fab
url is https://mp.weixin.qq.com/
Traceback (most recent call last):
  File "wxhub.py", line 472, in <module>
    main(Input.args.chrome)
  File "wxhub.py", line 443, in main
    raise Exception(f"获取网页失败!")
Exception: 获取网页失败!

**Comment by SeekPoint** [comment]
删除cookie好了
